const URLS = {
    all: 'all',
    add: 'add',
    edit: 'edit',
    info: 'info',
    signin: 'signin',
    forgotPassword: 'forgot-password',
    acceptInvite: 'accept-invite',
    home: 'dashboard',
    configuration: 'configuration',
    userManagement: 'user-management',
    tax: 'tax',
    generalInformation: 'general-information',
    products: 'products',
    variants: 'variants',
    categories: 'categories',
    newMainCategory: 'new-main',
    newSubCategory: 'new-sub',
    editMainCategory: 'edit-main',
    editSubCategory: 'edit-sub',
    newSuperSubCategory: 'new-super-sub',
    editSuperSubCategory: 'edit-super-sub',
    collections: 'collections',
    productGroups: 'product-groups',
    brands: 'brands',
    discounts: 'discounts',
    shipping: 'shipping',
    customers: 'customers',
    orders: 'orders',
    draftOrders: 'draft-orders',
    addChildOrder: 'add-child',
    editMainOrder: 'edit-main',
    editChildOrder: 'edit-child',
    pages: 'pages',
    homepage: 'homepage',
    vendors: 'vendors',
    navigations: 'navigations',
    headerCustomization: 'header-customization',
    footerCustomization: 'footer-customization',
    zones : 'zones',
    shippingRates : 'shipping-rates',
    defaultShipping : 'default-shipping',
    filters : 'filters',
    loyality:'loyality',
    coupons:'coupons',
    shippingRegions: 'shipping-regions',
    country: 'country',
    cities:'cities',
    checkoutCustomization: 'checkout-customization',
    contentApproval: 'content-approval',
    pushNotification: 'push-notification',
    sendNotification: 'send-notification'
}

export default URLS;