const URLS = {
    all: 'all',
    add: 'add',
    edit: 'edit',
    info: 'info',
    signin: 'signin',
    forgotPassword: 'forgot-password',
    acceptInvite: 'accept-invite',
    home: 'dashboard',
    configuration: 'configuration',
    userManagement: 'user-management',
    tax: 'tax',
    generalInformation: 'general-information',
    products: 'products',
    categories: 'categories',
    newMainCategory: 'new-main',
    newSubCategory: 'new-sub',
    editMainCategory: 'edit-main',
    editSubCategory: 'edit-sub',
    newSuperSubCategory: 'new-super-sub',
    editSuperSubCategory: 'edit-super-sub',
    collections: 'collections',
    productGroups: 'product-groups',
}

export default URLS;